[package]
name = "day13"
version = "0.1.0"
authors = ["jacquess <jacquess@bbd.co.za>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.13.3"
intcode = { path = "../intcode" }
